CREATE DATABASE PANDA_ENUM;

########################################################################################################

CREATE TABLE PANDA_ENUM.RELATION
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.RELATION (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.RELATION (LANGUAGE(2));

CREATE TABLE PANDA_ENUM.PROJ_STATUS
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.PROJ_STATUS (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.PROJ_STATUS (LANGUAGE(2));

CREATE TABLE PANDA_ENUM.WP_STATUS
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.WP_STATUS (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.WP_STATUS (LANGUAGE(2));

CREATE TABLE PANDA_ENUM.WI_STATUS
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.WI_STATUS (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.WI_STATUS (LANGUAGE(2));

CREATE TABLE PANDA_ENUM.WI_TYPE
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.WI_TYPE (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.WI_TYPE (LANGUAGE(2));

CREATE TABLE PANDA_ENUM.PRIORITY
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.PRIORITY (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.PRIORITY (LANGUAGE(2));

CREATE TABLE PANDA_ENUM.EDUCATION
(
	ID INT NOT NULL AUTO_INCREMENT,
	CODE NVARCHAR(5) NOT NULL,
	LANGUAGE NVARCHAR(3) NOT NULL,
	DESCRIPTION NVARCHAR(81),

	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE INDEX CODE_INDEX ON PANDA_ENUM.EDUCATION (CODE(4));
CREATE INDEX LANGUAGE_INDEX ON PANDA_ENUM.EDUCATION (LANGUAGE(2));

########################################################################################################

GRANT ALL ON PANDA_ENUM.* TO aenum@'%' IDENTIFIED BY 'aenumpass';
FLUSH PRIVILEGES;

########################################################################################################

USE PANDA_ENUM;

INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('OWNE', 'en', 'Project Director');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('OWNE', 'zh', '&#39033;&#30446;&#24635;&#30417;');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('MANA', 'en', 'Project Manager');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('MANA', 'zh', '&#39033;&#30446;&#32463;&#29702;');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('LEAD', 'en', 'Leader');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('LEAD', 'zh', '&#20027;&#31649;');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('MEMB', 'en', 'Member');
INSERT INTO RELATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('MEMB', 'zh', '&#25104;&#21592;');

INSERT INTO PROJ_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('NEWA', 'en', 'New');
INSERT INTO PROJ_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('NEWA', 'zh', '&#26032;&#24314;');
INSERT INTO PROJ_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('INPR', 'en', 'In Progress');
INSERT INTO PROJ_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('INPR', 'zh', '&#27491;&#22312;&#25191;&#34892;');
INSERT INTO PROJ_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('COMP', 'en', 'Complete');
INSERT INTO PROJ_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('COMP', 'zh', '&#32467;&#26463;');

INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('OPEN', 'en', 'Open');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('OPEN', 'zh', '&#26032;&#24314;');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('INPR', 'en', 'In Progress');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('INPR', 'zh', '&#27491;&#22312;&#25191;&#34892;');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('DONE', 'en', 'Done');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('DONE', 'zh', '&#23436;&#25104;');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('REOP', 'en', 'Re-open');
INSERT INTO WP_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('REOP', 'zh', '&#37325;&#26032;&#24320;&#21551;');

INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('OPEN', 'en', 'Open');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('OPEN', 'zh', '新建');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('INPR', 'en', 'In Progress');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('INPR', 'zh', '正在执行');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('NOTV', 'en', 'Not Valid');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('NOTV', 'zh', '无效');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('DONE', 'en', 'Done');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('DONE', 'zh', '完成');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('REOP', 'en', 'Re-open');
INSERT INTO WI_STATUS (CODE, LANGUAGE, DESCRIPTION) VALUES ('REOP', 'zh', '重新开启');

INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('TASK', 'en', 'Task');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('TASK', 'zh', '任务');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('DESI', 'en', 'Design');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('DESI', 'zh', '设计');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('NOTE', 'en', 'Note');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('NOTE', 'zh', '提醒');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('DEFE', 'en', 'Defect');
INSERT INTO WI_TYPE (CODE, LANGUAGE, DESCRIPTION) VALUES ('DEFE', 'zh', '缺陷');

INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('CRIT', 'en', 'Critical');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('CRIT', 'zh', '&#24613;');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('HIGH', 'en', 'High');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('HIGH', 'zh', '&#39640;');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('MEDI', 'en', 'Medium');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('MEDI', 'zh', '&#20013;');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('LOWA', 'en', 'Low');
INSERT INTO PRIORITY (CODE, LANGUAGE, DESCRIPTION) VALUES ('LOWA', 'zh', '&#20302;');

INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('DOCT', 'en', 'Doctor Degree');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('DOCT', 'zh', '&#21338;&#22763;');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('MAST', 'en', 'Master Degree');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('MAST', 'zh', '&#30805;&#22763;');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('BACH', 'en', 'Bachelor Degree');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('BACH', 'zh', '&#22823;&#23398;');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('COLL', 'en', 'College Diploma');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('COLL', 'zh', '&#22823;&#19987;');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('ZHON', 'zh', '&#20013;&#19987;');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('JIXI', 'zh', '&#25216;&#26657;');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('HIGH', 'en', 'High School Diploma');
INSERT INTO EDUCATION (CODE, LANGUAGE, DESCRIPTION) VALUES ('HIGH', 'zh', '&#39640;&#20013;');
