CREATE DATABASE PANDA_USER;

########################################################################################################

CREATE TABLE PANDA_USER.USER
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	LOGIN_EMAIL NVARCHAR(41) NOT NULL,
	PIC MEDIUMBLOB,
	LOGIN_PASS NVARCHAR(41) NOT NULL,
	FIRSTNAME NVARCHAR(41) NOT NULL,
	LASTNAME NVARCHAR(41) NOT NULL,
	FULLNAME_CN NVARCHAR(81) NOT NULL,
	REGISTER_TIME DATE NOT NULL,
	PROJ_ID INT UNSIGNED,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE UNIQUE INDEX LOGIN_EMAIL_INDEX ON PANDA_USER.USER (LOGIN_EMAIL);
CREATE INDEX FIRSTNAME_INDEX ON PANDA_USER.USER (FIRSTNAME(40));
CREATE INDEX LASTNAME_INDEX ON PANDA_USER.USER (LASTNAME(40));
CREATE INDEX FULLNAME_CN_INDEX ON PANDA_USER.USER (FULLNAME_CN(80));

########################################################################################################

CREATE TABLE PANDA_USER.INVI
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	FROM_ID INT UNSIGNED NOT NULL,
	TO_EMAIL NVARCHAR(41) NOT NULL,
	P_ID INT UNSIGNED NOT NULL,
	MESSAGE TEXT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	S_ID NVARCHAR(41) NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (FROM_ID) REFERENCES PANDA_USER.USER (ID)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE INDEX TO_EMAIL_INDEX ON PANDA_USER.INVI (TO_EMAIL);
CREATE INDEX P_ID_INDEX ON PANDA_USER.INVI (P_ID);
CREATE INDEX S_ID_INDEX ON PANDA_USER.INVI (S_ID(40));

########################################################################################################

GRANT ALL ON PANDA_USER.* TO auser@'%' IDENTIFIED BY 'auserpass';
FLUSH PRIVILEGES;